# Generated by Django 4.0.6 on 2022-08-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecredential',
            name='credential_type',
            field=models.CharField(
                max_length=255, null=True, verbose_name='Credential Used For'),
        ),
        migrations.AddField(
            model_name='stripecredential',
            name='environment',
            field=models.CharField(
                max_length=255, null=True, verbose_name='Is test or live?'),
        ),
    ]
