# Generated by Django 4.0.6 on 2022-08-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_card', '0004_stripetransaction_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransaction',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripecredential',
            name='environment',
            field=models.CharField(choices=[('TEST', 'TEST'), ('LIVE', 'LIVE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripetransaction',
            name='credential_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
