# Generated by Django 4.0.6 on 2022-08-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_card', '0005_stripetransaction_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransaction',
            name='customer_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripetransaction',
            name='transaction_status',
            field=models.CharField(choices=[('INITIATED', 'INITIATED'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], max_length=255),
        ),
    ]
