# Generated by Django 4.0.6 on 2022-08-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_card', '0006_stripetransaction_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransaction',
            name='payment_intent',
            field=models.JSONField(null=True),
        ),
    ]
