# Generated by Django 4.0.6 on 2022-08-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_card', '0007_stripetransaction_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripetransaction',
            name='status_code',
        ),
        migrations.AddField(
            model_name='stripetransaction',
            name='charge_object',
            field=models.JSONField(null=True),
        ),
    ]
