version: "3.9"
   
services:
  mysql:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql_volume:/var/lib/mysql"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    restart: unless-stopped
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    cap_add:
      - SYS_NICE 
    networks:
      - app-network
      
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    command: python -m gunicorn core.wsgi:application --bind 0.0.0.0:${BACKEND_APP_PORT}
    ports:
      - "${BACKEND_APP_PORT}:${BACKEND_APP_PORT}"
    restart: always
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - staticfiles:/app/staticfiles
    networks:
      - app-network

  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    tty: true
    volumes:
      - staticfiles:/app/staticfiles
      - ./frontend/dist:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_volume:
  staticfiles: