version: "3.9"
   
services:
  mysql:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql_volume:/var/lib/mysql"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    restart: unless-stopped
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    cap_add:
      - SYS_NICE 
      
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    command: python -m gunicorn core.wsgi:application --bind 0.0.0.0:${BACKEND_APP_PORT}
    ports:
      - "${BACKEND_APP_PORT}:${BACKEND_APP_PORT}"
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - staticfiles:/app/staticfiles
  
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   restart: always
  #   volumes:
  #     - frontend:/frontend/di
  #   ports:
  #     - "${FRONTEND_APP_PORT}:${FRONTEND_APP_PORT}"

  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    volumes:
      - staticfiles:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80

volumes:
  mysql_volume:
  staticfiles: