# Generated by Django 4.0.6 on 2022-08-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esewatransaction',
            name='oid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
