# Generated by Django 4.0.6 on 2022-08-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('esewa', '0003_remove_esewacredential_failure_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esewatransaction',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.app'),
        ),
    ]
