# Generated by Django 4.0.6 on 2022-08-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esewa', '0004_alter_esewatransaction_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esewatransaction',
            name='oid',
        ),
    ]
