# Generated by Django 4.0.6 on 2022-08-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imepay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imepaycredential',
            name='module',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
