# Generated by Django 4.0.6 on 2022-08-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imepay', '0004_alter_imepaytransaction_transaction_status'),
        ('imepay', '0004_imepaytransaction_token'),
    ]

    operations = [
    ]
