# Generated by Django 4.0.6 on 2022-08-03 09:32

from django.db import migrations, models
import django.db.models.deletion
import stripe_card.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaltiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=255, unique=True)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_status', models.CharField(choices=[('INITIATED', 'INITIATED'), ('PENDING', 'PENDING'), (
                    'COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('ERROR', 'ERROR')], max_length=255)),
                ('status_code', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('customer_email', models.CharField(max_length=255, null=True)),
                ('request_ip', models.CharField(max_length=255, null=True)),
                ('user_agent', models.CharField(max_length=255, null=True)),
                ('is_test', models.BooleanField(
                    default=False, verbose_name='Is test payment?')),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('customer_phone', models.CharField(max_length=15, null=True)),
                ('meta_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT, to='app.app')),
            ],
            bases=(models.Model, stripe_card.models.Transaction),
        ),
        migrations.CreateModel(
            name='KhaltiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT, to='app.app')),
            ],
        ),
    ]
