# Generated by Django 4.0.6 on 2022-08-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khalti', '0003_khaltitransaction_credential_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khaltitransaction',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='khalticredential',
            name='environment',
            field=models.CharField(choices=[('TEST', 'TEST'), ('LIVE', 'LIVE')], max_length=255, null=True, verbose_name='Is test or live?'),
        ),
        migrations.AlterField(
            model_name='khaltitransaction',
            name='credential_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
