# Generated by Django 4.0.6 on 2022-08-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khalti', '0005_alter_khaltitransaction_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khaltitransaction',
            name='status_code',
        ),
    ]
